version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app

  electron:
    build: .
    command: npm start
    environment:
      - OLLAMA_HOST=http://backend:5000
    ports:
      - "3000:3000"
      
  docs:
    image: jekyll/jekyll:4.2.2
    command: jekyll build --watch
    volumes:
      - ./docs:/srv/jekyll
      - ./docs/_site:/srv/jekyll/_site
    ports:
      - "4000:4000"
    environment:
      - JEKYLL_ENV=production
    depends_on:
      - backend
