title: Offline Doctor
description: AI-powered offline medical assistant
theme: jekyll-theme-cayman

baseurl: "/offlinedoctor"  # Update this to match your repository name
url: "https://lpolish.github.io"  # Update this to your GitHub Pages URL

# Jekyll settings
sass:
  style: compressed
  sass_dir: assets/css

# Navigation
navigation:
  - title: Home
    url: /
  - title: Getting Started
    url: /getting-started
  - title: Documentation
    url: /docs
  - title: Tutorials
    url: /tutorials
  - title: Download
    url: /download
  - title: FAQ
    url: /faq
  - title: Blog
    url: /blog
  - title: Community
    url: /community
  - title: GitHub
    url: https://github.com/lpolish/offlinedoctor

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# GitHub Pages specific settings
github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
  
# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata
  - README.md
  - vendor/bundle
