source "https://rubygems.org"

# GitHub Pages compatible version
gem "github-pages", group: :jekyll_plugins

# Jekyll plugins
gem "jekyll-theme-cayman"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
gem "jekyll-feed"

# Required for Ruby 3.0+
gem "webrick", "~> 1.8"

# Fix Faraday retry warning
gem "faraday-retry"

# Windows and JRuby compatibility
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

# Lock `http_parser.rb` gem to `v0.6.x` on JRuby builds
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
