source "https://rubygems.org"

# Use a stable Jekyll version that works well with GitHub Pages
gem "jekyll", "~> 4.2.2"
gem "jekyll-theme-cayman"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
gem "jekyll-feed", "~> 0.12"

# Required for Ruby 3.0+
gem "webrick", "~> 1.7"

# Windows and JRuby compatibility
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

# Lock `http_parser.rb` gem to `v0.6.x` on JRuby builds
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
